import { MonumentBasic } from '../../../core/types/common';

// Ánh xạ ảnh thumbnail chính thức theo từng mã di tích (tương ứng với classes.json)
export const MONUMENT_THUMBNAIL_MAP: Record<string, string> = {
  BNR: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236384/tmb_bnr.jpg',
  CBT: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236443/tmb_cbt.jpg',
  CMC: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235651/tmb_cmc.jpg',
  CauHienLuong: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235676/tmb_chl.jpg',
  DDCC: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235759/tmb_ddcc.jpg',
  DenHung: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235851/tmb_denh.jpg',
  DinhDocLap: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235910/tmb_ddl.jpg',
  LangChuTichHCM: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235980/tmb_lbac.jpg',
  NgoMon: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236028/tmb_nmon.jpg',
  NhaThoDB: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236114/tmb_ntho.jpg',
  NTCD: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236180/tmb_ntu.jpg',
  TDiaMS: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236221/tmb_tdms.jpg',
  ThanhCoQT: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236265/tmb_tcoqt.jpg',
  VanMieuQTG: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236553/tmb_vm.jpg',
};

// 14 di tích theo đúng thứ tự classes.json (0 - 13):
export const ALL_MAP_MONUMENTS: MonumentBasic[] = [
  {
    id: 'BNR',
    name: 'Bến Nhà Rồng',
    location: 'Phường Khánh Hội, Thành phố Hồ Chí Minh',
    region: 'Nam',
    coordinates: {
      lat: 10.7681,
      lng: 106.7067,
      xPercent: 55,
      yPercent: 85,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236384/tmb_bnr.jpg',
    shortDescription: 'Nơi người thanh niên yêu nước Nguyễn Tất Thành ra đi tìm đường cứu nước năm 1911, nay là Bảo tàng Hồ Chí Minh.',
  },
  {
    id: 'CBT',
    name: 'Chợ Bến Thành',
    location: 'Phường Bến Thành, Thành phố Hồ Chí Minh',
    region: 'Nam',
    coordinates: {
      lat: 10.7725,
      lng: 106.6980,
      xPercent: 53,
      yPercent: 83,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236443/tmb_cbt.jpg',
    shortDescription: 'Biểu tượng văn hóa thương mại hơn 100 năm tuổi với tháp đồng hồ bốn mặt đặc trưng giữa lòng thành phố.',
  },
  {
    id: 'CMC',
    name: 'Chùa Một Cột',
    location: 'Phường Ba Đình, Thành phố Hà Nội',
    region: 'Bắc',
    coordinates: {
      lat: 21.0358,
      lng: 105.8335,
      xPercent: 47,
      yPercent: 19,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235651/tmb_cmc.jpg',
    shortDescription: 'Ngôi chùa hình đóa sen ngát hương độc nhất vô nhị dựng trên một trụ đá, biểu tượng Phật giáo ngàn năm thời Lý.',
  },
  {
    id: 'CauHienLuong',
    name: 'Cầu Hiền Lương - Sông Bến Hải',
    location: 'Xã Vĩnh Linh, Tỉnh Quảng Trị',
    region: 'Trung',
    coordinates: {
      lat: 17.0086,
      lng: 107.0544,
      xPercent: 58,
      yPercent: 40,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235676/tmb_chl.jpg',
    shortDescription: 'Chứng nhân lịch sử vĩ đại nơi vĩ tuyến 17 chia cắt đất nước ròng rã hơn 20 năm, biểu tượng của khát vọng hòa bình thống nhất.',
  },
  {
    id: 'DDCC',
    name: 'Địa đạo Củ Chi',
    location: 'Xã An Nhơn Tây, Thành phố Hồ Chí Minh',
    region: 'Nam',
    coordinates: {
      lat: 11.1408,
      lng: 106.4632,
      xPercent: 48,
      yPercent: 79,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235759/tmb_ddcc.jpg',
    shortDescription: 'Hệ thống hầm ngầm huyền thoại dài hơn 250km, "thành phố trong lòng đất" kiên cường trong kháng chiến giải phóng dân tộc.',
  },
  {
    id: 'DenHung',
    name: 'Đền Hùng',
    location: 'Xã Hy Cương, Tỉnh Phú Thọ',
    region: 'Bắc',
    coordinates: {
      lat: 21.3653,
      lng: 105.3256,
      xPercent: 44,
      yPercent: 15,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235851/tmb_denh.jpg',
    shortDescription: 'Khu di tích lịch sử quốc gia đặc biệt cội nguồn tổ tiên dân tộc Việt Nam, nơi thờ tự các vị Vua Hùng dựng nước.',
  },
  {
    id: 'DinhDocLap',
    name: 'Dinh Độc Lập',
    location: 'Phường Bến Thành, Thành phố Hồ Chí Minh',
    region: 'Nam',
    coordinates: {
      lat: 10.7770,
      lng: 106.6954,
      xPercent: 52,
      yPercent: 82,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235910/tmb_ddl.jpg',
    shortDescription: 'Di tích lịch sử đặc biệt ghi dấu trọn vẹn thời khắc lịch sử trưa ngày 30/4/1975 non sông thu về một mối.',
  },
  {
    id: 'LangChuTichHCM',
    name: 'Lăng Chủ tịch Hồ Chí Minh',
    location: 'Phường Ba Đình, Thành phố Hà Nội',
    region: 'Bắc',
    coordinates: {
      lat: 21.0368,
      lng: 105.8347,
      xPercent: 49,
      yPercent: 17,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789235980/tmb_lbac.jpg',
    shortDescription: 'Nơi an nghỉ vĩnh hằng của Chủ tịch Hồ Chí Minh vĩ đại, tọa lạc trang nghiêm bên Quảng trường Ba Đình lịch sử.',
  },
  {
    id: 'NgoMon',
    name: 'Cố đô Huế (Ngọ Môn)',
    location: 'Phường Phú Xuân, Thành phố Huế',
    region: 'Trung',
    coordinates: {
      lat: 16.4697,
      lng: 107.5796,
      xPercent: 62,
      yPercent: 44,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236028/tmb_nmon.jpg',
    shortDescription: 'Cổng chính phía Nam của Hoàng thành Huế với lầu Ngũ Phụng tuyệt tác kiến trúc cung đình triều Nguyễn uy nghi.',
  },
  {
    id: 'NhaThoDB',
    name: 'Nhà Thờ Đức Bà',
    location: 'Phường Sài Gòn, Thành phố Hồ Chí Minh',
    region: 'Nam',
    coordinates: {
      lat: 10.7798,
      lng: 106.6990,
      xPercent: 54,
      yPercent: 82,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236114/tmb_ntho.jpg',
    shortDescription: 'Vương cung thánh đường tuyệt đẹp mang phong cách Romanesque cải biên pha nét Gothic giữa trung tâm Sài Gòn.',
  },
  {
    id: 'NTCD',
    name: 'Nhà Tù Côn Đảo',
    location: 'Đặc khu Côn Đảo, Thành phố Hồ Chí Minh',
    region: 'Nam',
    coordinates: {
      lat: 8.6835,
      lng: 106.608,
      xPercent: 56,
      yPercent: 93,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236180/tmb_ntu.jpg',
    shortDescription: 'Di tích Lịch sử Quốc gia Đặc biệt Nhà tù Côn Đảo - Biểu tượng bất diệt cho ý chí quật cường và khát vọng tự do của dân tộc.',
  },
  {
    id: 'TDiaMS',
    name: 'Thánh Địa Mỹ Sơn',
    location: 'Xã Thu Bồn, Thành phố Đà Nẵng',
    region: 'Trung',
    coordinates: {
      lat: 15.7958,
      lng: 108.1244,
      xPercent: 66,
      yPercent: 48,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236221/tmb_tdms.jpg',
    shortDescription: 'Quần thể đền tháp Chăm Pa cổ kính giữa thung lũng huyền bí, di sản văn hóa thế giới được UNESCO vinh danh.',
  },
  {
    id: 'ThanhCoQT',
    name: 'Thành Cổ Quảng Trị',
    location: 'Phường Quảng Trị, Tỉnh Quảng Trị',
    region: 'Trung',
    coordinates: {
      lat: 16.7533,
      lng: 107.1906,
      xPercent: 60,
      yPercent: 42,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236265/tmb_tcoqt.jpg',
    shortDescription: 'Di tích quốc gia đặc biệt ghi dấu 81 ngày đêm rực lửa mùa hè 1972, bản hùng ca bất tử của chủ nghĩa anh hùng cách mạng.',
  },
  {
    id: 'VanMieuQTG',
    name: 'Văn Miếu Quốc Tử Giám',
    location: 'Phường Văn Miếu - Quốc Tử Giám, Thành phố Hà Nội',
    region: 'Bắc',
    coordinates: {
      lat: 21.0278,
      lng: 105.8358,
      xPercent: 54,
      yPercent: 18,
    },
    thumbnailUrl: 'https://res.cloudinary.com/inwwexot/image/upload/v1789236553/tmb_vm.jpg',
    shortDescription: 'Trường đại học đầu tiên của Việt Nam với 82 Bia Tiến sĩ nghìn năm văn hiến được UNESCO vinh danh Di sản tư liệu thế giới.',
  },
];
